version: 2
build:
  os: ubuntu-24.04
  apt_packages:
    - clang
  tools:
    python: "3.12"
    rust: "latest"
  jobs:
    post_checkout:
      # unshallow so version can be derived from tag
      - git fetch --unshallow || true
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
