# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

import numpy
import numpy.typing

class CodecPipelineImpl:
    def __new__(
        cls,
        metadata,
        *,
        validate_checksums=...,
        store_empty_chunks=...,
        chunk_concurrent_minimum=...,
        chunk_concurrent_maximum=...,
        num_threads=...,
    ): ...
    def retrieve_chunks_and_apply_index(
        self,
        chunk_descriptions: typing.Sequence[
            tuple[
                tuple[str, typing.Sequence[int], str, typing.Sequence[int]],
                typing.Sequence[slice],
                typing.Sequence[slice],
            ]
        ],
        value: numpy.NDArray[typing.Any],
    ) -> None: ...
    def retrieve_chunks(
        self,
        chunk_descriptions: typing.Sequence[
            tuple[str, typing.Sequence[int], str, typing.Sequence[int]]
        ],
    ) -> list[numpy.typing.NDArray[numpy.uint8]]: ...
    def store_chunks_with_indices(
        self,
        chunk_descriptions: typing.Sequence[
            tuple[
                tuple[str, typing.Sequence[int], str, typing.Sequence[int]],
                typing.Sequence[slice],
                typing.Sequence[slice],
            ]
        ],
        value: numpy.NDArray[typing.Any],
    ) -> None: ...
