name: ci

on:
  push:
      branches:
        - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  build_and_test:
    name: build and test
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable"]  # "nightly"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Rust in GH runner images can lag behind stable releases + act does not include Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          components: rustfmt

      - name: Install rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.19"
          enable-cache: true
          cache-dependency-glob:  |
            pyproject.toml
            Cargo.toml

      - name: Install python deps + Build
        run: |
          uv pip install --system -e . --group dev --verbose

      - name: Python Tests
        run: pytest -n auto

      - name: Rust Tests
        run: cargo test

      - name: Check formatting
        # see “Type hints” section in contributing.md
        run: |
          cargo run --bin stub_gen
          pre-commit run --all-files --show-diff-on-failure || true
          git diff --exit-code HEAD
